//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_usuarios()
        {
            this.tb_videos = new HashSet<tb_videos>();
        }
    
        public int id_usuario { get; set; }
        public Nullable<int> id_usuario_perfil { get; set; }
        public string tx_nome { get; set; }
        public string tx_email { get; set; }
        public string tx_login { get; set; }
        public string tx_senha { get; set; }
        public Nullable<int> in_creditos { get; set; }
    
        public virtual tb_usuario_perfil tb_usuario_perfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_videos> tb_videos { get; set; }
    }
}
