//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_videos
    {
        public int id_video { get; set; }
        public string tx_link_video { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual tb_usuarios tb_usuarios { get; set; }
    }
}
